# Awesome Copilot Configuration File
# Generated on 2025-09-21T02:25:46.196Z
# 
# This file allows you to enable/disable specific prompts, instructions, 
# chat modes, and collections for your project.
#
# Set items to 'true' to include them in your project
# Set items to 'false' to exclude them
#
# After configuring, run: awesome-copilot apply
#

version: "1.0"
project:
  name: "My Project"
  description: "A project using awesome-copilot customizations"
  output_directory: ".awesome-copilot"
prompts:
  ai-prompt-engineering-safety-review: false
  architecture-blueprint-generator: false
  aspnet-minimal-api-openapi: false
  az-cost-optimize: false
  azure-resource-health-diagnose: false
  boost-prompt: false
  breakdown-epic-arch: false
  breakdown-epic-pm: false
  breakdown-feature-implementation: false
  breakdown-feature-prd: false
  breakdown-plan: false
  breakdown-test: false
  clojure-add-to-memory: false
  code-exemplars-blueprint-generator: false
  comment-code-generate-a-tutorial: false
  containerize-aspnet-framework: false
  containerize-aspnetcore: false
  copilot-instructions-blueprint-generator: false
  cosmosdb-datamodeling: false
  create-agentsmd: false
  create-architectural-decision-record: false
  create-github-action-workflow-specification: false
  create-github-issue-feature-from-specification: false
  create-github-issues-feature-from-implementation-plan: false
  create-github-issues-for-unmet-specification-requirements: false
  create-github-pull-request-from-specification: false
  create-implementation-plan: false
  create-llms: false
  create-oo-component-documentation: false
  create-readme: false
  create-specification: false
  create-spring-boot-java-project: false
  create-spring-boot-kotlin-project: false
  create-technical-spike: false
  csharp-async: false
  csharp-docs: false
  csharp-mstest: false
  csharp-nunit: false
  csharp-tunit: false
  csharp-xunit: false
  declarative-agents: false
  documentation-writer: false
  dotnet-best-practices: false
  dotnet-design-pattern-review: false
  editorconfig: false
  ef-core: false
  first-ask: false
  folder-structure-blueprint-generator: false
  gen-specs-as-issues: false
  generate-custom-instructions-from-codebase: false
  git-flow-branch-creator: false
  java-docs: false
  java-junit: false
  java-springboot: false
  javascript-typescript-jest: false
  kotlin-springboot: false
  mkdocs-translations: false
  multi-stage-dockerfile: false
  my-issues: false
  my-pull-requests: false
  next-intl-add-language: false
  playwright-automation-fill-in-form: false
  playwright-explore-website: false
  playwright-generate-test: false
  postgresql-code-review: false
  postgresql-optimization: false
  project-workflow-analysis-blueprint-generator: false
  prompt-builder: false
  readme-blueprint-generator: false
  remember: false
  remember-interactive-programming: false
  repo-story-time: false
  review-and-refactor: false
  sql-code-review: false
  sql-optimization: false
  suggest-awesome-github-copilot-chatmodes: false
  suggest-awesome-github-copilot-prompts: false
  technology-stack-blueprint-generator: false
  update-avm-modules-in-bicep: false
  update-implementation-plan: false
  update-llms: false
  update-markdown-file-index: false
  update-oo-component-documentation: false
  update-specification: false
instructions:
  a11y: false
  ai-prompt-engineering-safety-best-practices: false
  angular: false
  aspnet-rest-apis: false
  azure-devops-pipelines: false
  azure-functions-typescript: false
  azure-logic-apps-power-automate: false
  azure-verified-modules-terraform: false
  bicep-code-best-practices: false
  blazor: false
  clojure-memory: false
  cmake-vcpkg: false
  coldfusion-cfc: false
  coldfusion-cfm: false
  collections: false
  containerization-docker-best-practices: false
  convert-jpa-to-spring-data-cosmos: false
  copilot-thought-logging: false
  csharp: false
  csharp-ja: false
  csharp-ko: false
  dart-n-flutter: false
  declarative-agents-microsoft365: false
  devbox-image-definition: false
  devops-core-principles: false
  dotnet-architecture-good-practices: false
  dotnet-framework: false
  dotnet-maui: false
  dotnet-wpf: false
  genaiscript: false
  generate-modern-terraform-code-for-azure: false
  gilfoyle-code-review: false
  github-actions-ci-cd-best-practices: false
  go: false
  java: false
  joyride-user-project: false
  joyride-workspace-automation: false
  kubernetes-deployment-best-practices: false
  localization: false
  markdown: false
  memory-bank: false
  ms-sql-dba: false
  nestjs: false
  nextjs: false
  nextjs-tailwind: false
  nodejs-javascript-vitest: false
  object-calisthenics: false
  oqtane: false
  performance-optimization: false
  playwright-python: false
  playwright-typescript: false
  power-apps-canvas-yaml: false
  power-platform-connector: false
  powershell: false
  powershell-pester-5: false
  python: false
  quarkus: false
  quarkus-mcp-server-sse: false
  reactjs: false
  ruby-on-rails: false
  rust: false
  security-and-owasp: false
  self-explanatory-code-commenting: false
  spec-driven-workflow-v1: false
  springboot: false
  sql-sp-generation: false
  taming-copilot: false
  tanstack-start-shadcn-tailwind: false
  task-implementation: false
  tasksync: false
  terraform: false
  vuejs3: false
chatmodes:
  4.1-Beast: false
  Thinking-Beast-Mode: false
  Ultimate-Transparent-Thinking-Beast-Mode: false
  accesibility: false
  address-comments: false
  api-architect: false
  atlassian-requirements-to-jira: false
  azure-logic-apps-expert: false
  azure-principal-architect: false
  azure-saas-architect: false
  azure-verified-modules-bicep: false
  azure-verified-modules-terraform: false
  bicep-implement: false
  bicep-plan: false
  blueprint-mode: false
  clojure-interactive-programming: false
  critical-thinking: false
  csharp-dotnet-janitor: false
  debug: false
  declarative-agents-architect: false
  demonstrate-understanding: false
  electron-angular-native: false
  expert-dotnet-software-engineer: false
  expert-react-frontend-engineer: false
  gilfoyle: false
  implementation-plan: false
  janitor: false
  kusto-assistant: false
  mentor: false
  meta-agentic-project-scaffold: false
  microsoft-study-mode: false
  microsoft_learn_contributor: false
  ms-sql-dba: false
  plan: false
  planner: false
  playwright-tester: false
  postgresql-dba: false
  prd: false
  principal-software-engineer: false
  prompt-builder: false
  prompt-engineer: false
  refine-issue: false
  research-technical-spike: false
  rust-gpt-4.1-beast-mode: false
  semantic-kernel-dotnet: false
  semantic-kernel-python: false
  simple-app-idea-generator: false
  software-engineer-agent-v1: false
  specification: false
  task-planner: false
  task-researcher: false
  tdd-green: false
  tdd-red: false
  tdd-refactor: false
  tech-debt-remediation-plan: false
  voidbeast-gpt41enhanced: false
  wg-code-alchemist: false
  wg-code-sentinel: false
collections:
  azure-cloud-development: false
  csharp-dotnet-development: false
  database-data-management: true
  devops-oncall: false
  frontend-web-dev: true
  project-planning: true
  security-best-practices: true
  technical-spike: true
  testing-automation: true
