global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Game Backend Services
  - job_name: 'prototype-game-gateway'
    static_configs:
      - targets: ['prototype-game:8080']
    metrics_path: '/metrics'
    scrape_interval: 5s
    params:
      format: ['prometheus']

  - job_name: 'prototype-game-simulation'
    static_configs:
      - targets: ['prototype-game:8081']
    metrics_path: '/metrics'
    scrape_interval: 5s
    params:
      format: ['prometheus']

  # System Metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 5s

  # Database Metrics
  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 10s

  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 10s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - "alerts.yml"