name: "Bug"
description: "Something is broken or regressed"
title: "bug: "
labels: ["bug"]
body:
  - type: textarea
    id: desc
    attributes:
      label: Description
      description: What happened? What did you expect?
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Reproduction
      description: Steps and exact commands/inputs to reproduce.
      placeholder: |
        1. make run
        2. TOKEN=$(make -s login)
        3. make wsprobe TOKEN=$TOKEN MOVE_X=1
        4. Observe …
  - type: input
    id: version
    attributes:
      label: SHA/Version
      placeholder: git rev-parse --short HEAD
  - type: dropdown
    id: severity
    attributes:
      label: Severity
      options:
        - S1 - Crash/data loss
        - S2 - Major
        - S3 - Minor
        - S4 - Cosmetic
  - type: input
    id: env
    attributes:
      label: Environment
      placeholder: OS, Go version, etc.

