blank_issues_enabled: false
contact_links:
  - name: Developer Guide
    url: https://github.com/AstroSteveo/prototype-game/blob/main/docs/dev/DEV.md
    about: Build, run, and test commands
  - name: Backlog
    url: https://github.com/AstroSteveo/prototype-game/blob/main/docs/process/BACKLOG.md
    about: User stories and milestones

