name: "Decision Panel"
description: Facilitate a high‑impact architectural decision; output an ADR
title: "decision: <topic>"
labels: ["adr", "architecture", "process"]
body:
  - type: markdown
    attributes:
      value: |
        Use with `docs/process/sessions/DECISION_PANEL.md`. Assign an ADR author and capture follow‑ups.

  - type: input
    id: goal
    attributes:
      label: Goal / Success Criteria
      placeholder: e.g., Reduce server broadcast fan‑out by 40% without degrading latency
    validations:
      required: true

  - type: textarea
    id: options
    attributes:
      label: Options Considered
      placeholder: Option A — pros/cons; Option B — pros/cons; …
    validations:
      required: true

  - type: textarea
    id: decision
    attributes:
      label: Decision & Rationale
      placeholder: Chosen option and why. Include reversibility and risk.
    validations:
      required: true

  - type: input
    id: adr
    attributes:
      label: ADR Path
      placeholder: docs/process/adr/0002-<slug>.md
    validations:
      required: true

  - type: textarea
    id: followups
    attributes:
      label: Follow‑up Issue Checklist
      placeholder: |
        - [ ] Implement X
        - [ ] Add tests Y
        - [ ] Update docs Z
    validations:
      required: true
