name: "Roadmap Planning Meeting"
description: Plan and review the roadmap for the next release cycle
title: "roadmap: Next Release Planning - YYYY-MM-DD"
labels: ["roadmap", "planning", "process"]
body:
  - type: markdown
    attributes:
      value: Use with `docs/process/sessions/ROADMAP.md`. Schedule this meeting quarterly or before major releases.

  - type: textarea
    id: current_state
    attributes:
      label: Current State Assessment
      placeholder: |
        Progress on current milestone:
        - Feature A: Complete
        - Feature B: 75% done, on track
        
        Technical health:
        - Performance issues: None
        - Technical debt: Refactoring needed in module X
        
        User feedback highlights:
        - Users love feature Y
        - Pain point with feature Z
    validations:
      required: true

  - type: textarea
    id: release_vision
    attributes:
      label: Next Release Vision
      placeholder: |
        Release theme: "Enhanced User Experience"
        
        Core objectives:
        - Improve onboarding flow
        - Add multiplayer features
        - Optimize performance
        
        Success metrics:
        - User retention: +15%
        - Performance: <500ms load time
        - New feature adoption: >60%
    validations:
      required: true

  - type: textarea
    id: candidate_features
    attributes:
      label: Candidate Features
      placeholder: |
        High Priority:
        - [ ] Feature 1 (Impact: High, Effort: Medium)
        - [ ] Feature 2 (Impact: Medium, Effort: Low)
        
        Medium Priority:
        - [ ] Feature 3 (Impact: Medium, Effort: High)
        - [ ] Feature 4 (Impact: Low, Effort: Low)
        
        Technical Improvements:
        - [ ] Infrastructure upgrade
        - [ ] Performance optimization
        - [ ] Security enhancements
    validations:
      required: true

  - type: textarea
    id: timeline_estimates
    attributes:
      label: Timeline & Resource Estimates
      placeholder: |
        Proposed timeline: 8 weeks
        
        Key milestones:
        - Week 2: Design phase complete
        - Week 4: Core development 50%
        - Week 6: Feature complete, testing begins
        - Week 8: Release ready
        
        Resource requirements:
        - Developers: 3 FTE
        - Designers: 1 FTE
        - QA: 1 FTE
    validations:
      required: true

  - type: textarea
    id: risks_dependencies
    attributes:
      label: Risks & Dependencies
      placeholder: |
        Risks:
        - External API changes (Medium risk)
        - Team capacity during holidays (Low risk)
        
        Dependencies:
        - Third-party library update
        - Infrastructure migration completion
        
        Mitigation strategies:
        - Buffer time in schedule
        - Backup plans for critical dependencies
    validations:
      required: false

  - type: checkboxes
    id: meeting_outcomes
    attributes:
      label: Meeting Outcomes
      options:
        - label: Release goals and theme defined
        - label: Features prioritized and selected
        - label: Timeline and milestones established
        - label: Risks identified with mitigation plans
        - label: Resource requirements confirmed
        - label: Project board updated with roadmap items
        - label: Stakeholder communication plan created
        - label: Next planning session scheduled