name: "Story"
description: "User story with acceptance criteria and tests"
title: "US-### — "
labels: ["story"]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What is the user value? Keep it concise.
      placeholder: As a <player/dev>, I want <goal> so that <value>.
    validations:
      required: true
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: Bullet list of verifiable behaviors.
      placeholder: |
        - [ ] Given … when … then …
        - [ ] …
    validations:
      required: true
  - type: textarea
    id: tests
    attributes:
      label: Test Notes
      description: Unit/WS integration cases and perf budgets.
      placeholder: e.g., `make test-ws` asserts cadence 100ms ±20ms; payload <30KB/s.
  - type: input
    id: points
    attributes:
      label: Estimate (points)
      placeholder: "1, 2, 3, 5, 8"
  - type: dropdown
    id: milestone
    attributes:
      label: Milestone
      options:
        - M1
        - M2
        - M3
        - M4
        - M5
        - Stretch
    validations:
      required: false
  - type: input
    id: links
    attributes:
      label: Related Docs/PRs
      placeholder: docs/process/BACKLOG.md row, design notes, etc.

