name: "Task"
description: "Technical task or refactor"
title: "task: "
labels: ["task"]
body:
  - type: textarea
    id: scope
    attributes:
      label: Scope
      description: What needs doing and why.
    validations:
      required: true
  - type: textarea
    id: done
    attributes:
      label: Definition of Done
      placeholder: e.g., docs updated, tests added, CI green.

