name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test:
    name: Build, Vet, Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.x'
          cache: true
      - name: Format (gofmt)
        run: |
          make fmt
          git diff --exit-code
      - name: Vet
        run: make vet
      - name: Unit tests
        run: make test

  ws-tests:
    name: WS-Tagged Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.x'
          cache: true
      - name: WS tests (-tags ws)
        run: make test-ws

