name: backend-ci

on:
  push:
    branches: [ main ]
  pull_request:

permissions: read-all

jobs:
  build-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go 1.23.x
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.x'
          check-latest: true
          cache: true

      - name: Go version
        run: go version

      - name: Tidy
        run: go mod tidy

      - name: Vet
        run: go vet ./...

      - name: Test
        run: go test ./...

      - name: Test (ws tag)
        run: go test -tags ws ./...
